openapi: 3.0.0
info:
  title: CustomerProductandServiceDirectory_X
  x-ibm-name: CustomerProductandServiceDirectory_X
  description: |
    API para la creación de cuentas de clientes (PN) de tipo CUENTA AHORRO (AHOR) y CUENTA CORRIENTE (CCTE), alineada a especificación BIAN.
  version: 1.0.0
  contact:
    name: Líder de Producto
    email: lider.producto@empresa.com
  x-plataforma: IBM API Connect
  x-endpoints:
    desarrollo: https://gw.dev.dombifaws.com/dev/int/x/v1.0/customerproductandservicedirectory/product/natural/register
    certificacion: https://gw.qas.dombifaws.com/qas/int/x/v1.0/customerproductandservicedirectory/product/natural/register
    produccion: https://gw.dombifaws.com/api/int/x/v1.0/customerproductandservicedirectory/product/natural/register

servers:
  - url: https://gw.dev.dombifaws.com/dev/int
    description: Desarrollo
  # - url: https://gw.qas.dombifaws.com/qas/int
  #   description: Certificación
  # - url: https://gw.dombifaws.com/api/int
  #   description: Producción

tags:
  - name: CustomerProductandServiceDirectory
    description: Operaciones BIAN para Customer Product and Service Directory

paths:
  /x/v1.0/customerproductandservicedirectory/product/natural/register:
    post:
      tags:
        - CustomerProductandServiceDirectory
      summary: Registrar cuenta de cliente (PN) - BIAN
      description: Permite la creación de la cuenta de un cliente (PN), de tipo CUENTA AHORRO (AHOR) y CUENTA CORRIENTE (CCTE), alineado a BIAN.
      operationId: registerCustomerProductandServiceDirectoryProductNatural
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegisterCustomerProductandServiceDirectoryProductNatural'
            example:
              RegisterCustomerProductandServiceDirectoryProductNatural:
                ServiceType: "S00003"
                CustomerReference: "000000000"
                ProductIdentification: "ANWS"
                CurrencyCode: "SOL"
                PartyRoleCode: "000001112"
      responses:
        '200':
          description: Registro exitoso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RegisterCustomerProductandServiceDirectoryProductNaturalResponse'
              example:
                RegisterCustomerProductandServiceDirectoryProductNaturalResponse:
                  CustomerReference: "000000000"
                  AccountNumber: 8028036210
                  ProductIdentification: "ANWS"
                  CurrencyCode: "SOL"
                  Branch:
                    Identification: "100"
                  PartyRoleCode: "000001112"
                  IBAN: "03820110802803621005"
                  OpeningDate: "20240115"
                  OpeningTime: "114000"
        '400':
          description: Error de validación de campos obligatorios
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RegisterCustomerProductandServiceDirectoryProductNaturalError'
              example:
                RegisterCustomerProductandServiceDirectoryProductNaturalResponse:
                  Status: "ERROR"
                  StatusCode: "-1"
                  Message: "Validación de campos obligatorios fallida."
        '401':
          description: No autorizado
        '500':
          description: Error interno del servidor

components:
  schemas:
    RegisterCustomerProductandServiceDirectoryProductNatural:
      type: object
      properties:
        RegisterCustomerProductandServiceDirectoryProductNatural:
          type: object
          required:
            - ServiceType
            - CustomerReference
            - ProductIdentification
            - CurrencyCode
            - PartyRoleCode
          properties:
            ServiceType:
              type: string
              example: "S00003"
            CustomerReference:
              type: string
              example: "000000000"
            ProductIdentification:
              type: string
              example: "ANWS"
            CurrencyCode:
              type: string
              example: "SOL"
            PartyRoleCode:
              type: string
              example: "000001112"

    RegisterCustomerProductandServiceDirectoryProductNaturalResponse:
      type: object
      properties:
        RegisterCustomerProductandServiceDirectoryProductNaturalResponse:
          type: object
          properties:
            CustomerReference:
              type: string
              example: "000000000"
            AccountNumber:
              type: integer
              example: 8028036210
            ProductIdentification:
              type: string
              example: "ANWS"
            CurrencyCode:
              type: string
              example: "SOL"
            Branch:
              type: object
              properties:
                Identification:
                  type: string
                  example: "100"
            PartyRoleCode:
              type: string
              example: "000001112"
            IBAN:
              type: string
              example: "03820110802803621005"
            OpeningDate:
              type: string
              example: "20240115"
            OpeningTime:
              type: string
              example: "114000"

    RegisterCustomerProductandServiceDirectoryProductNaturalError:
      type: object
      properties:
        RegisterCustomerProductandServiceDirectoryProductNaturalResponse:
          type: object
          properties:
            Status:
              type: string
              example: "ERROR"
            StatusCode:
              type: string
              example: "-1"
            Message:
              type: string
              example: "Validación de campos obligatorios fallida."

  securitySchemes:
    OAuth2:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: https://gw.dev.banbif.com.pe/dev/ext/banbifoauth/oauth2/token
          scopes:
            accounts:write: Crear cuentas

security:
  - OAuth2: [accounts:write]